version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=fdY6C6DGt9-li=aPlJSZ
    ports:
      - "9200:9200"
      - "9300:9300"
        volumes:
      - es_data:/usr/share/elasticsearch/data
  backend:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - elasticsearch
  volumes:
    es_data: